# Generated by Django 3.0.2 on 2020-01-22 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Datamatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='unknown', max_length=100)),
                ('image_path', models.CharField(default='data/images/', max_length=100)),
                ('zip_path', models.CharField(default='data/zips/', max_length=100)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dm_app.Session')),
            ],
        ),
    ]
